services:
  app:
    container_name: clipper
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${PORT-8000}"
    restart: unless-stopped