version: '3.8'

services:
  app:
    container_name: clipper
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:8000"
    restart: unless-stopped